### PR TITLE
Update readme to reference brew recipe

### PR DESCRIPTION
**Pull request by edwardloveall**
Also cleaned up a little bit of the readme formatting.

### CODE REVIEW

**Comment by KingOfBrian** [comment]
This is fantastic @edwardloveall ! I took a break from eject for a few and totally forgot about this. How do I update homebrew when I make a new release?

**Comment by edwardloveall** [comment]
Pretty simple, just follow the steps here: https://github.com/Homebrew/homebrew-core/blob/26825c7b2dc7aafa9f0ed85af968441ca465e918/CONTRIBUTING.md#submit-a-123-version-upgrade-for-the-foo-formula

Copied here for posterity:

### Submit a `1.2.3` version upgrade for the `foo` formula

* check if the same upgrade has been already submitted by [searching the open pull requests for `foo`](https://github.com/Homebrew/homebrew-core/pulls?utf8=✓&q=is%3Apr+is%3Aopen+foo).
* `brew edit foo`
* edit [`url`](http://www.rubydoc.info/github/Homebrew/brew/master/Formula#url-class_method) and [`sha256`](http://www.rubydoc.info/github/Homebrew/brew/master/Formula#sha256%3D-class_method)/[`tag`](http://www.rubydoc.info/github/Homebrew/brew/master/Formula#url-class_method), leave the [`bottle`](http://www.rubydoc.info/github/Homebrew/brew/master/Formula#bottle-class_method) as-is
* `brew install --build-from-source foo`
* run `brew audit --strict foo` and fix any issues
* `git commit` with commit subject `foo 1.2.3`
* [open a pull request](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) and fix any failing tests

**Comment by KingOfBrian** [comment]
Just made a PR with an update. Much more painful than Cocoapods to update, but magic enough.

**Comment by edwardloveall** [comment]
Yeah they do some weird things. If you don't like their approval process, there's always private taps that you can manage yourself. You could have a raiz tap with all your projects for example.

**Pull request merged**
